### ISSUE TITLE
How to use other middleware with it?

### ISSUE THREAD

**Issue by tutyamxx** [calvintwr/express-routemagic#11]
Hey, I was wondering how to use other middleware using this module?

Example - I have this endpoint

```
router.get('/testacl'. acl.middleware(), (req, res, next) => { });
```

The code above will say acl is not found even though is set up properly in `app.js`

**Comment by calvintwr** [comment]
@tutyamxx Internally, what it does is to go through your directories and do all the requires.

Does your code work when you require the routings via the standard express way?

Perhaps you can share a larger chunk of your code with me?

**Comment by tutyamxx** [comment]
The code works the standard way, but using the routes inside the `app.js` where I declared it. See the docs [for ACL here](https://www.npmjs.com/package/acl2). While using express-routemagic, It can't find it, for some reason. Unfortunately, I can't share the large chunk of code, but hopefully if you check the url I mentioned, it might make some sense?

**Comment by calvintwr** [comment]
Ok let me get to it. I’ll update you.

**Comment by calvintwr** [comment]
@tutyamxx I have verified that middlewares will continue to work.

I suspect what happened is that you didn't declare acl in your routings, nor separate them into their own routing files to begin with. If this is the error here, you have to re-declare acl. See as follows:

### Everything inside app.js
When you do a router.get inside of app.js, acl is within scope:
```js
// app.js
const acl = new ACL()
router.get('/testacl'. acl.middleware(), (req, res, next) => { })
```

### Re-declaring modules when separating routing code from app.js
But acl is not within scope of your routing files if you separate them. You need to re-declare them in each of the routing files:
```js
//testacl.js
const acl = require('somewhere/where/ACL/is/initialised')
const router = require('express').Router()

router.get('/', (req, res, next) => {})

module.exports = router
```

```js
// app.js
app.use('/testacl', require('./routes/testacl'))
```

**Comment by tutyamxx** [comment]
thank you for the information, not sure what I did wrong but IM GLAD IT WORKS, definitely trying to see the error on my side... 

EDIT: You meant
```javascript
// app.js
const acl = new ACL();
```

```javascript
//testacl.js
const acl = require('app.js') // initialized here
const router = require('express').Router()

router.get('/', acl.middleware(), (req, res, next) => {})

module.exports = router
```

rather than

```javascript
//testacl.js
const acl = require('app.js') // initialized here
const router = require('express').Router()

router.get('/', (req, res, next) => {})

module.exports = router
``` 

?

I'm slightly confused

**Comment by calvintwr** [comment]
@tutyamxx yup that’s right. Just redeclare acl in your routing files and you will be alright.

alternatively, if you need it for all your routes, do:

```js
//app.js
const acl = new ACL() //initialise it correctly.

app.use(acl.middleware()) // this has to be above #magic.use, so that all requests gos through this before the routings.

magic.use(app)

```

**Comment by tutyamxx** [comment]
I only use it in some specific endpoints. My vscode doesn't even find the autocompletion for `middleware()` in the routings :-s

I get `TypeError: acl.middleware is not a function` using the sample provided by you

**Comment by tutyamxx** [comment]
Here, a sample to test.

```javascript
// app.js

const express = require('express')
const app = express()
const port = 3000
const routesMagic = require('express-routemagic');
const ACL2 = require("acl2");// same as acl, just maintained
const acl = new ACL2(new ACL2.memoryBackend()); // bladybla, it will show user not authenticated

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
})

// below, works fine as you said
//app.get('/testacl', acl.middleware(), (req, res, next) => { })

// --| Enable automatic routing for everything in the routes folder
routesMagic.use(app, {
    routesFolder: 'routes',
    invokerPath: __dirname,
    allowSameName: true,
    ignoreSuffix: ['_bak', '_old', '_dev']
});

module.exports = app;
```

but in `routes/testacl.js`

```javascript
//testacl.js
const acl = require('../app.js') // initialized above in app.js
const router = require('express').Router()

router.get('/', acl.middleware(), (req, res, next) => {
    res.send("hello world");
});

module.exports = router;

```

^ throws 

```
router.get('/', acl.middleware(), (req, res, next) => {
                    ^

TypeError: acl.middleware is not a function
```

**Comment by calvintwr** [comment]
@tutyamxx thanks for the code.

It is what it says. `acl` is out of scope because you didn’t provide it. Doing:
```js
const acl = require('../app.js')
```
Doesn’t put acl in scope. That require gives you the express `app` instance, and not acl. You can console log to see that.

This is an express thing. There’s 2 ways use a middleware.

1. If everything or a lot of your routes needs to push through acl:
```js

// routes that don’t need to pass through acl should be in separate folder
// if all your routes need acl, omit this.
magic.use(app, {
    routesFolder: 'routes_no_acl'
})

// now use acl to protect whatever that’s below it
app.use(acl.middleware())

// and everything below here has passed through acl
magic.use(app) // this will require the routes in the 'routes' folder by default
```
Watch out for folder path collision between the two. If you define the same paths in the two, the one below will overwrite. It’s just how express works.

2. Only few routes need acl:
Use `app.locals` to pass `acl` into the scope of the routes
```js
// app.js
const app = express()
app.locals = acl

magic.use(app)
```
```js
// routes/testacl.is
const app = require('../app.js') // initialized above in app.js
const router = require('express').Router()

router.get('/', app.locals.acl.middleware(), (req, res, next) => {
    res.send("hello world");
});

module.exports = router;

```

**Comment by tutyamxx** [comment]
Thanks for the explanation, very kind of you, however second method you provided does throw again saying `TypeError: Cannot read properties of undefined (reading 'acl')`. I'm losing my bloody mind 😂

**Comment by calvintwr** [comment]
Add me on skype calvin.twr

I’ll fix it for you

**Comment by tutyamxx** [comment]
Unfortunately I don't have skype. I need to understand why is it not working lol, because I've used your second version (did you test it?)

After more digging, why it doesn't work, i tried to console.log `app.locals` in `testacl.js` and i got ```(node:5692) Warning: Accessing non-existent property 'locals' of module exports inside circular dependency```


Here's my code, nothing more, nothing less.

```javascript
//app.js

const express = require('express')
const app = express()
const port = 3000
const routesMagic = require('express-routemagic');

const Acl = require('acl2');
const acl = new Acl(new Acl.memoryBackend()); // bladybla, it will show user not authenticated
app.locals = acl;

// --| Enable automatic routing for everything in the routes folder
routesMagic.use(app, {
    routesFolder: 'routes',
    invokerPath: __dirname,
    allowSameName: true,
    ignoreSuffix: ['_bak', '_old', '_dev']
});

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
})

module.exports = app;
```

and 

```javascript
//routes/testacl.js
const app = require('../app.js') // initialized here
const router = require('express').Router();

router.get('/', app.locals.acl.middleware(), (req, res, next) => {
    res.send("hello world");
});

module.exports = router;
```

now, try to run it on your machine. Perhaps it's a OS pathing again?

**Comment by calvintwr** [comment]
I didn't set up acl. However I realised that my app.locals example is incorrect.

Can you do this instead?:

Set up acl modularly:
```js
// apps/acl.js
const ACL2 = require("acl2");// same as acl, just maintained
const acl = new ACL2(new ACL2.memoryBackend()); // bladybla, it will show user not authenticated

module.exports = acl
```

```js
// routes/testacl.is
const router = require('express').Router();
const acl = require('../apps/acl');

router.get('/', acl.middleware(), (req, res, next) => {
    res.send("hello world");
});

module.exports = router;
```

**Comment by tutyamxx** [comment]
Works, thanks for the support kind human!

**Comment by calvintwr** [comment]
No worries mate easy.
