### ISSUE TITLE
Last question about pathing

### ISSUE THREAD

**Issue by tutyamxx** [calvintwr/express-routemagic#12]
Hi, using your module, as far as I understand it, works wonders, no doubt about that. But what if I want to access the `req.path` ? an endpoint like `public/test/test.js` will log the `req.path` as `/`. Any idea how to get the actual path for the actual endpoint?

**Comment by calvintwr** [comment]
Does this work?

https://stackoverflow.com/questions/12525928/how-to-get-request-path-with-express-req-object

**Comment by tutyamxx** [comment]
Yes sir. Thanks. We should add a small FAQ in the repo readme because many people will have both "questions/issues" I opened. 

Solution for this was: `req.originalUrl`
