### ISSUE TITLE
Typscript support

### ISSUE THREAD

**Issue by imprakharshukla** [calvintwr/express-routemagic#4]
Hey! This seems like an interesting idea but I had troubles setting this up with Typescript. Maybe add docs for the same? Thanks.

**Comment by calvintwr** [comment]
Can I check what’s your code? And I will see what’s the issue.

**Comment by calvintwr** [comment]
@imprakharshukla

**Comment by imprakharshukla** [comment]
@calvintwr Hey! Sorry for not replying but I migrated away to using my own yet a similar approach. I will update this thread in the future if I ever get a chance to use express-routemagic.
