### ISSUE TITLE
TypeError: Router.use() requires a middleware function but got a Object

### ISSUE THREAD

**Issue by emiljamel** [calvintwr/express-routemagic#5]
Hi calvintwr! I encountered a problem when I used es6 syntax when exporting the module. Is there any way to fix this?

module.export = router (success)
export default router (failed)

**Comment by calvintwr** [comment]
Can you share your code with me? I’ll get it working/fixed 😊

**Comment by emiljamel** [comment]
Yes, of course. https://github.com/emiljamel/testing

**Comment by calvintwr** [comment]
Should be fixed, please check! @emiljamel
